In [2]:
import pandas as pd
import re

In [6]:
dogs = pd.read_csv(r'Downloads/ShelterDogs.csv')

In [7]:
dogs.head()

,ID,name,age,sex,breed,date_found,adoptable_from,posted,color,coat,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
0,23807,Gida,0.25,female,Unknown Mix,2019-12-10,2019-12-11,2019-12-11,red,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,533,Frida És Ricsi,0.17,female,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,black and white,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
2,23793,NaN,4.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,saddle back,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23795,NaN,1.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,yellow-brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,23806,Amy,2.00,female,French Bulldog Mix,2019-12-10,2019-12-11,2019-12-11,black,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
dogs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2937 entries, 0 to 2936
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 2937 non-null   int64
 1   name               2845 non-null   object
 2   age                2937 non-null   float64
 3   sex                2937 non-null   object
 4   breed              2937 non-null   object
 5   date_found         2937 non-null   object
 6   adoptable_from     2937 non-null   object
 7   posted             2937 non-null   object
 8   color              2937 non-null   object
 9   coat               2937 non-null   object
 10  size               2937 non-null   object
 11  neutered           1852 non-null   object
 12  housebroken        460 non-null    object
 13  likes_people       1999 non-null   object
 14  likes_children     1219 non-null   object
 15  get_along_males    1633 non-null   object
 16  get_along_females  1673 non-null   object
 17  get_along_cats     431 non-null    object
 18  keep_in            1916 non-null   object
dtypes: float64(1), int64(1), object(17)
memory usage: 436.1+ KB

In [11]:
dogs['date_found'] = pd.to_datetime(dogs['date_found'])
dogs

,ID,name,age,sex,breed,date_found,adoptable_from,posted,color,coat,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
0,23807,Gida,0.25,female,Unknown Mix,2019-12-10,2019-12-11,2019-12-11,red,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,533,Frida És Ricsi,0.17,female,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,black and white,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
2,23793,NaN,4.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,saddle back,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23795,NaN,1.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,yellow-brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,23806,Amy,2.00,female,French Bulldog Mix,2019-12-10,2019-12-11,2019-12-11,black,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2932,118,Fodri,16.92,male,Unknown Mix,2003-12-25,2003-12-25,2006-03-22,yellow-brown,short,medium,no,no,yes,yes,no,yes,no,garden
2933,262,Csibi,17.33,female,Staffordshire Terrier Mix,2004-08-27,2004-08-27,2005-07-08,striped,short,large,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2934,4,Konrád,18.17,male,Unknown Mix,2005-09-21,2005-09-21,2005-10-26,black,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2935,141,Kölni,17.17,male,Unknown Mix,2004-11-27,2004-11-27,2005-05-02,black and brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2936,248,Kedves,16.08,male,"German Shepherd Dog, Hound Mix",2005-04-02,2005-04-02,2005-06-30,sable,short,medium,yes,NaN,yes,NaN,yes,yes,NaN,both flat and garden

In [63]:
dogs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2937 entries, 0 to 2936
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 2937 non-null   int64
 1   name               2845 non-null   object
 2   age                2937 non-null   float64
 3   sex                2937 non-null   object
 4   dog_breed          2937 non-null   object
 5   date_found         2937 non-null   datetime64[ns]
 6   date_adoptable     2937 non-null   datetime64[ns]
 7   date_posted        2937 non-null   datetime64[ns]
 8   color              2937 non-null   object
 9   coat_type          2937 non-null   object
 10  size               2937 non-null   object
 11  neutered           1852 non-null   object
 12  housebroken        460 non-null    object
 13  likes_people       1999 non-null   object
 14  likes_children     1219 non-null   object
 15  get_along_males    1633 non-null   object
 16  get_along_females  1673 non-null   object
 17  get_along_cats     431 non-null    object
 18  keep_in            1916 non-null   object
dtypes: datetime64[ns](3), float64(1), int64(1), object(14)
memory usage: 436.1+ KB

In [6]:
dogs.shape

(2937, 19)

In [10]:
name = dogs.name
print(name.head())

0              Gida
1    Frida És Ricsi
2               NaN
3               NaN
4               Amy
Name: name, dtype: object

In [12]:
type_breed = dogs[['name', 'sex', 'breed']]
type_breed.head()

             name     sex               breed
0            Gida  female         Unknown Mix
1  Frida És Ricsi  female         Unknown Mix
2             NaN    male         Unknown Mix
3             NaN    male         Unknown Mix
4             Amy  female  French Bulldog Mix

In [14]:
dogs.iloc[1]

ID                               533
name                  Frida És Ricsi
age                             0.17
sex                           female
breed                    Unknown Mix
date_found                2019-12-01
adoptable_from            2019-12-01
posted                    2019-12-09
color                black and white
coat                           short
size                           small
neutered                          no
housebroken                      NaN
likes_people                     yes
likes_children                   yes
get_along_males                  yes
get_along_females                yes
get_along_cats                   yes
keep_in                          NaN
Name: 1, dtype: object

In [15]:
dogs.iloc[3:7]

,ID,name,age,sex,breed,date_found,adoptable_from,posted,color,coat,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
3,23795,NaN,1.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,yellow-brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,23806,Amy,2.00,female,French Bulldog Mix,2019-12-10,2019-12-11,2019-12-11,black,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,23801,Alex,4.25,male,Unknown Mix,2019-12-09,2019-12-24,2019-12-09,yellow-brown,short,small,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,534,Ricsi És Frida,0.17,male,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,brown,short,small,no,NaN,yes,yes,yes,yes,yes,NaN

In [16]:
dogs.iloc[:10]

,ID,name,age,sex,breed,date_found,adoptable_from,posted,color,coat,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
0,23807,Gida,0.25,female,Unknown Mix,2019-12-10,2019-12-11,2019-12-11,red,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,533,Frida És Ricsi,0.17,female,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,black and white,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
2,23793,NaN,4.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,saddle back,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23795,NaN,1.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,yellow-brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,23806,Amy,2.00,female,French Bulldog Mix,2019-12-10,2019-12-11,2019-12-11,black,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,23801,Alex,4.25,male,Unknown Mix,2019-12-09,2019-12-24,2019-12-09,yellow-brown,short,small,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,534,Ricsi És Frida,0.17,male,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,brown,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
7,23805,NaN,0.17,female,Unknown Mix,2019-12-10,2019-12-25,2019-12-11,gray and white,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,23809,NaN,0.17,female,Unknown Mix,2019-12-11,2019-12-26,2019-12-12,black,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1801,Újhartyáni Mazsi,0.17,female,Unknown Mix,2019-12-10,2019-12-10,2019-12-11,brown and white,short,small,no,NaN,yes,yes,yes,yes,yes,flat

In [17]:
dogs.iloc[-2:]

,ID,name,age,sex,breed,date_found,adoptable_from,posted,color,coat,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
2935,141,Kölni,17.17,male,Unknown Mix,2004-11-27,2004-11-27,2005-05-02,black and brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2936,248,Kedves,16.08,male,"German Shepherd Dog, Hound Mix",2005-04-02,2005-04-02,2005-06-30,sable,short,medium,yes,NaN,yes,NaN,yes,yes,NaN,both flat and garden

In [18]:
dogs.rename(columns = {'posted' : 'date_posted', 
                         'breed' : 'dog_breed',
                         'adoptable_from' : 'date_adoptable',
                         'coat' : 'coat_type'},
                         inplace = True)

In [21]:
dogs.head()

,ID,name,age,sex,dog_breed,date_found,date_adoptable,date_posted,color,coat_type,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
0,23807,Gida,0.25,female,Unknown Mix,2019-12-10,2019-12-11,2019-12-11,red,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,533,Frida És Ricsi,0.17,female,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,black and white,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
2,23793,NaN,4.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,saddle back,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23795,NaN,1.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,yellow-brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,23806,Amy,2.00,female,French Bulldog Mix,2019-12-10,2019-12-11,2019-12-11,black,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
female = dogs[dogs.sex == 'female']
female

,ID,name,age,sex,dog_breed,date_found,date_adoptable,date_posted,color,coat_type,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
0,23807,Gida,0.25,female,Unknown Mix,2019-12-10,2019-12-11,2019-12-11,red,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,533,Frida És Ricsi,0.17,female,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,black and white,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
4,23806,Amy,2.00,female,French Bulldog Mix,2019-12-10,2019-12-11,2019-12-11,black,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,23805,NaN,0.17,female,Unknown Mix,2019-12-10,2019-12-25,2019-12-11,gray and white,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,23809,NaN,0.17,female,Unknown Mix,2019-12-11,2019-12-26,2019-12-12,black,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2923,356,Barbara,13.75,female,Unknown Mix,2006-06-01,2006-06-01,2006-06-28,black and brown,short,medium,no,NaN,NaN,yes,yes,yes,NaN,both flat and garden
2926,109,Kari,13.33,female,"German Pointer, Pointer Mix",2007-01-15,2007-01-15,2007-03-16,black and white,short,medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2930,389,Pötyi,14.25,female,"German Pointer, Greyhound, Pointer Mix",2006-08-01,2006-08-01,2006-08-20,black and white,short,medium,yes,NaN,NaN,NaN,NaN,NaN,NaN,both flat and garden
2931,362,Tündér,14.75,female,Labrador Retriever Mix,2006-05-01,2006-05-01,2006-06-28,apricot,medium,medium,yes,NaN,NaN,yes,yes,yes,NaN,both flat and garden
2933,262,Csibi,17.33,female,Staffordshire Terrier Mix,2004-08-27,2004-08-27,2005-07-08,striped,short,large,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
breeds = dogs[dogs.dog_breed != 'Unknown Mix']
breeds

,ID,name,age,sex,dog_breed,date_found,date_adoptable,date_posted,color,coat_type,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
4,23806,Amy,2.00,female,French Bulldog Mix,2019-12-10,2019-12-11,2019-12-11,black,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1222,Vasi,3.67,male,Vizsla Mix,2019-10-25,2019-10-25,2019-12-12,red,short,medium,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,532,Fickó,1.50,male,"Bull Terrier, Dachshund Mix",2019-12-01,2019-12-01,2019-12-09,brown and white,short,medium,yes,NaN,yes,yes,no,no,no,NaN
20,23788,Sába,7.58,female,Kuvasz,2019-12-01,2019-12-16,2019-12-08,white,medium,large,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,4491,Bethany,5.00,female,Chinese Shar-Pei Mix,2019-11-28,2019-11-28,2019-12-07,black and brown,short,medium,NaN,NaN,yes,NaN,NaN,NaN,NaN,both flat and garden
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2928,110,Kavics,13.75,male,Pumi Mix,2007-01-15,2007-01-15,2007-03-17,striped,medium,medium,NaN,NaN,yes,yes,yes,yes,NaN,both flat and garden
2930,389,Pötyi,14.25,female,"German Pointer, Greyhound, Pointer Mix",2006-08-01,2006-08-01,2006-08-20,black and white,short,medium,yes,NaN,NaN,NaN,NaN,NaN,NaN,both flat and garden
2931,362,Tündér,14.75,female,Labrador Retriever Mix,2006-05-01,2006-05-01,2006-06-28,apricot,medium,medium,yes,NaN,NaN,yes,yes,yes,NaN,both flat and garden
2933,262,Csibi,17.33,female,Staffordshire Terrier Mix,2004-08-27,2004-08-27,2005-07-08,striped,short,large,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2936,248,Kedves,16.08,male,"German Shepherd Dog, Hound Mix",2005-04-02,2005-04-02,2005-06-30,sable,short,medium,yes,NaN,yes,NaN,yes,yes,NaN,both flat and garden

In [29]:
over_two = dogs[dogs.age > 2]
over_two

,ID,name,age,sex,dog_breed,date_found,date_adoptable,date_posted,color,coat_type,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
2,23793,NaN,4.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,saddle back,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,23801,Alex,4.25,male,Unknown Mix,2019-12-09,2019-12-24,2019-12-09,yellow-brown,short,small,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1222,Vasi,3.67,male,Vizsla Mix,2019-10-25,2019-10-25,2019-12-12,red,short,medium,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,23797,NaN,5.00,female,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,brown,long,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,23796,NaN,8.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,black,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2932,118,Fodri,16.92,male,Unknown Mix,2003-12-25,2003-12-25,2006-03-22,yellow-brown,short,medium,no,no,yes,yes,no,yes,no,garden
2933,262,Csibi,17.33,female,Staffordshire Terrier Mix,2004-08-27,2004-08-27,2005-07-08,striped,short,large,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2934,4,Konrád,18.17,male,Unknown Mix,2005-09-21,2005-09-21,2005-10-26,black,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2935,141,Kölni,17.17,male,Unknown Mix,2004-11-27,2004-11-27,2005-05-02,black and brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2936,248,Kedves,16.08,male,"German Shepherd Dog, Hound Mix",2005-04-02,2005-04-02,2005-06-30,sable,short,medium,yes,NaN,yes,NaN,yes,yes,NaN,both flat and garden

In [34]:
four_and_under = dogs[dogs.age < 4]
four_and_under

,ID,name,age,sex,dog_breed,date_found,date_adoptable,date_posted,color,coat_type,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
0,23807,Gida,0.25,female,Unknown Mix,2019-12-10,2019-12-11,2019-12-11,red,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,533,Frida És Ricsi,0.17,female,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,black and white,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
3,23795,NaN,1.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,yellow-brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,23806,Amy,2.00,female,French Bulldog Mix,2019-12-10,2019-12-11,2019-12-11,black,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,534,Ricsi És Frida,0.17,male,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,brown,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
906,1445,Gixer,3.92,male,Unknown Mix,2016-01-19,2016-01-19,2016-03-15,saddle back,short,medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
910,1441,Gréta,3.92,female,Unknown Mix,2016-01-19,2016-01-19,2016-03-15,black and brown,medium,medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
911,1442,Garbó,3.92,male,Unknown Mix,2016-01-19,2016-01-19,2016-03-15,brown,long,medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
912,1448,Gamma,3.92,female,Unknown Mix,2016-01-19,2016-01-19,2016-03-15,brown,short,medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
917,1444,Glenda,3.92,female,Unknown Mix,2016-01-19,2016-01-19,2016-03-15,black,short,medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
likes_people = dogs[(dogs.likes_people == 'yes') & (dogs.likes_children == 'yes')]
likes_people

,ID,name,age,sex,dog_breed,date_found,date_adoptable,date_posted,color,coat_type,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
1,533,Frida És Ricsi,0.17,female,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,black and white,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
6,534,Ricsi És Frida,0.17,male,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,brown,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
9,1801,Újhartyáni Mazsi,0.17,female,Unknown Mix,2019-12-10,2019-12-10,2019-12-11,brown and white,short,small,no,NaN,yes,yes,yes,yes,yes,flat
13,1800,Újhartyáni Frenki,0.17,male,Unknown Mix,2019-12-10,2019-12-10,2019-12-11,tricolor,short,small,no,NaN,yes,yes,yes,yes,yes,flat
14,532,Fickó,1.50,male,"Bull Terrier, Dachshund Mix",2019-12-01,2019-12-01,2019-12-09,brown and white,short,medium,yes,NaN,yes,yes,no,no,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2918,6,Fifi,13.67,female,German Shepherd Dog Mix,2007-04-01,2007-04-01,2007-05-21,sable,short,medium,yes,NaN,yes,yes,yes,yes,NaN,NaN
2919,12,Kitty,15.67,female,Kuvasz,2005-04-01,2004-04-01,2007-07-23,white,medium,large,yes,NaN,yes,yes,yes,yes,NaN,garden
2925,427,Yuki,13.75,male,German Shepherd Dog Mix,2006-06-01,2006-06-01,2006-11-29,red,short,medium,yes,NaN,yes,yes,yes,yes,no,both flat and garden
2928,110,Kavics,13.75,male,Pumi Mix,2007-01-15,2007-01-15,2007-03-17,striped,medium,medium,NaN,NaN,yes,yes,yes,yes,NaN,both flat and garden
2932,118,Fodri,16.92,male,Unknown Mix,2003-12-25,2003-12-25,2006-03-22,yellow-brown,short,medium,no,no,yes,yes,no,yes,no,garden

In [13]:
cats_female = dogs[(dogs.get_along_females == 'yes') | (dogs.get_along_cats == 'yes')]
cats_female

,ID,name,age,sex,breed,date_found,adoptable_from,posted,color,coat,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
1,533,Frida És Ricsi,0.17,female,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,black and white,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
6,534,Ricsi És Frida,0.17,male,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,brown,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
9,1801,Újhartyáni Mazsi,0.17,female,Unknown Mix,2019-12-10,2019-12-10,2019-12-11,brown and white,short,small,no,NaN,yes,yes,yes,yes,yes,flat
13,1800,Újhartyáni Frenki,0.17,male,Unknown Mix,2019-12-10,2019-12-10,2019-12-11,tricolor,short,small,no,NaN,yes,yes,yes,yes,yes,flat
16,1802,Újhartyáni Bori,0.17,female,Unknown Mix,2019-12-10,2019-12-10,2019-12-11,tricolor,short,small,no,NaN,yes,yes,yes,yes,yes,flat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,427,Yuki,13.75,male,German Shepherd Dog Mix,2006-06-01,2006-06-01,2006-11-29,red,short,medium,yes,NaN,yes,yes,yes,yes,no,both flat and garden
2928,110,Kavics,13.75,male,Pumi Mix,2007-01-15,2007-01-15,2007-03-17,striped,medium,medium,NaN,NaN,yes,yes,yes,yes,NaN,both flat and garden
2931,362,Tündér,14.75,female,Labrador Retriever Mix,2006-05-01,2006-05-01,2006-06-28,apricot,medium,medium,yes,NaN,NaN,yes,yes,yes,NaN,both flat and garden
2932,118,Fodri,16.92,male,Unknown Mix,2003-12-25,2003-12-25,2006-03-22,yellow-brown,short,medium,no,no,yes,yes,no,yes,no,garden
2936,248,Kedves,16.08,male,"German Shepherd Dog, Hound Mix",2005-04-02,2005-04-02,2005-06-30,sable,short,medium,yes,NaN,yes,NaN,yes,yes,NaN,both flat and garden

In [40]:
suitable = dogs[(dogs.neutered == 'yes') & (dogs.age >= 4)]
suitable

,ID,name,age,sex,dog_breed,date_found,date_adoptable,date_posted,color,coat_type,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
5,23801,Alex,4.25,male,Unknown Mix,2019-12-09,2019-12-24,2019-12-09,yellow-brown,short,small,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,23788,Sába,7.58,female,Kuvasz,2019-12-01,2019-12-16,2019-12-08,white,medium,large,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,1048,Velencei Fiffi,9.25,female,Afghan Hound,2019-12-01,2019-12-04,2019-12-03,brown,long,medium,yes,yes,yes,NaN,NaN,NaN,NaN,flat
46,2154,Kormi,6.50,male,Unknown Mix,2019-10-07,2019-10-07,2019-12-05,black,short,medium,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,1049,Velencei Shyne On,8.42,female,American Bulldog,2019-12-01,2019-12-04,2019-12-03,striped,short,medium,yes,yes,yes,NaN,NaN,NaN,NaN,both flat and garden
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,427,Yuki,13.75,male,German Shepherd Dog Mix,2006-06-01,2006-06-01,2006-11-29,red,short,medium,yes,NaN,yes,yes,yes,yes,no,both flat and garden
2930,389,Pötyi,14.25,female,"German Pointer, Greyhound, Pointer Mix",2006-08-01,2006-08-01,2006-08-20,black and white,short,medium,yes,NaN,NaN,NaN,NaN,NaN,NaN,both flat and garden
2931,362,Tündér,14.75,female,Labrador Retriever Mix,2006-05-01,2006-05-01,2006-06-28,apricot,medium,medium,yes,NaN,NaN,yes,yes,yes,NaN,both flat and garden
2933,262,Csibi,17.33,female,Staffordshire Terrier Mix,2004-08-27,2004-08-27,2005-07-08,striped,short,large,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2936,248,Kedves,16.08,male,"German Shepherd Dog, Hound Mix",2005-04-02,2005-04-02,2005-06-30,sable,short,medium,yes,NaN,yes,NaN,yes,yes,NaN,both flat and garden

In [42]:
breed = dogs[(dogs.dog_breed.isin(['Staffordshire Terrier Mix', 'Labrador Retriever Mix', 'German Shepherd Dog Mix']))]
breed

,ID,name,age,sex,dog_breed,date_found,date_adoptable,date_posted,color,coat_type,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
26,4486,Cotta,0.15,female,Staffordshire Terrier Mix,2019-12-01,2019-12-01,2019-12-07,brown and white,short,medium,NaN,NaN,yes,NaN,yes,yes,NaN,both flat and garden
27,4488,Kehlani,0.42,female,German Shepherd Dog Mix,2019-12-01,2019-12-01,2019-12-07,black and brown,short,medium,NaN,NaN,yes,NaN,NaN,NaN,NaN,both flat and garden
34,4485,Panna,0.15,female,Staffordshire Terrier Mix,2019-12-01,2019-12-01,2019-12-07,striped,short,medium,NaN,NaN,yes,NaN,yes,yes,NaN,both flat and garden
62,1791,Dabasi Bors,1.00,male,Staffordshire Terrier Mix,2019-11-28,2019-11-28,2019-11-28,brown,short,medium,no,NaN,yes,yes,yes,yes,NaN,both flat and garden
86,23754,NaN,1.00,male,Staffordshire Terrier Mix,2019-11-25,2019-12-10,2019-11-25,black and white,short,medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2917,14,Kormi,17.67,male,German Shepherd Dog Mix,2003-04-01,2004-04-01,2007-07-23,black,short,medium,no,NaN,yes,yes,yes,yes,NaN,garden
2918,6,Fifi,13.67,female,German Shepherd Dog Mix,2007-04-01,2007-04-01,2007-05-21,sable,short,medium,yes,NaN,yes,yes,yes,yes,NaN,NaN
2925,427,Yuki,13.75,male,German Shepherd Dog Mix,2006-06-01,2006-06-01,2006-11-29,red,short,medium,yes,NaN,yes,yes,yes,yes,no,both flat and garden
2931,362,Tündér,14.75,female,Labrador Retriever Mix,2006-05-01,2006-05-01,2006-06-28,apricot,medium,medium,yes,NaN,NaN,yes,yes,yes,NaN,both flat and garden
2933,262,Csibi,17.33,female,Staffordshire Terrier Mix,2004-08-27,2004-08-27,2005-07-08,striped,short,large,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
dogs[(dogs.dog_breed.isin(['Staffordshire Terrier Mix', 'Labrador Retriever Mix', 'German Shepherd Dog Mix']))].reset_index()

,index,ID,name,age,sex,dog_breed,date_found,date_adoptable,date_posted,color,coat_type,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
0,26,4486,Cotta,0.15,female,Staffordshire Terrier Mix,2019-12-01,2019-12-01,2019-12-07,brown and white,short,medium,NaN,NaN,yes,NaN,yes,yes,NaN,both flat and garden
1,27,4488,Kehlani,0.42,female,German Shepherd Dog Mix,2019-12-01,2019-12-01,2019-12-07,black and brown,short,medium,NaN,NaN,yes,NaN,NaN,NaN,NaN,both flat and garden
2,34,4485,Panna,0.15,female,Staffordshire Terrier Mix,2019-12-01,2019-12-01,2019-12-07,striped,short,medium,NaN,NaN,yes,NaN,yes,yes,NaN,both flat and garden
3,62,1791,Dabasi Bors,1.00,male,Staffordshire Terrier Mix,2019-11-28,2019-11-28,2019-11-28,brown,short,medium,no,NaN,yes,yes,yes,yes,NaN,both flat and garden
4,86,23754,NaN,1.00,male,Staffordshire Terrier Mix,2019-11-25,2019-12-10,2019-11-25,black and white,short,medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,2917,14,Kormi,17.67,male,German Shepherd Dog Mix,2003-04-01,2004-04-01,2007-07-23,black,short,medium,no,NaN,yes,yes,yes,yes,NaN,garden
331,2918,6,Fifi,13.67,female,German Shepherd Dog Mix,2007-04-01,2007-04-01,2007-05-21,sable,short,medium,yes,NaN,yes,yes,yes,yes,NaN,NaN
332,2925,427,Yuki,13.75,male,German Shepherd Dog Mix,2006-06-01,2006-06-01,2006-11-29,red,short,medium,yes,NaN,yes,yes,yes,yes,no,both flat and garden
333,2931,362,Tündér,14.75,female,Labrador Retriever Mix,2006-05-01,2006-05-01,2006-06-28,apricot,medium,medium,yes,NaN,NaN,yes,yes,yes,NaN,both flat and garden
334,2933,262,Csibi,17.33,female,Staffordshire Terrier Mix,2004-08-27,2004-08-27,2005-07-08,striped,short,large,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
neutered_known = dogs.loc[dogs.neutered.notnull()]
neutered_known

,ID,name,age,sex,dog_breed,date_found,date_adoptable,date_posted,color,coat_type,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
0,23807,Gida,0.25,female,Unknown Mix,2019-12-10,2019-12-11,2019-12-11,red,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,533,Frida És Ricsi,0.17,female,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,black and white,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
2,23793,NaN,4.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,saddle back,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23795,NaN,1.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,yellow-brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,23806,Amy,2.00,female,French Bulldog Mix,2019-12-10,2019-12-11,2019-12-11,black,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2932,118,Fodri,16.92,male,Unknown Mix,2003-12-25,2003-12-25,2006-03-22,yellow-brown,short,medium,no,no,yes,yes,no,yes,no,garden
2933,262,Csibi,17.33,female,Staffordshire Terrier Mix,2004-08-27,2004-08-27,2005-07-08,striped,short,large,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2934,4,Konrád,18.17,male,Unknown Mix,2005-09-21,2005-09-21,2005-10-26,black,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2935,141,Kölni,17.17,male,Unknown Mix,2004-11-27,2004-11-27,2005-05-02,black and brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2936,248,Kedves,16.08,male,"German Shepherd Dog, Hound Mix",2005-04-02,2005-04-02,2005-06-30,sable,short,medium,yes,NaN,yes,NaN,yes,yes,NaN,both flat and garden

In [48]:
neutered_unknown = dogs.loc[dogs.neutered.isnull()]
neutered_unknown

,ID,name,age,sex,dog_breed,date_found,date_adoptable,date_posted,color,coat_type,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
21,4492,Döme,1.00,male,Unknown Mix,2019-11-25,2019-11-25,2019-12-07,black,medium,medium,NaN,NaN,yes,NaN,NaN,NaN,yes,both flat and garden
22,4484,Jocelyn,0.17,female,Unknown Mix,2019-11-27,2019-11-27,2019-12-07,apricot,short,small,NaN,NaN,yes,NaN,yes,yes,NaN,both flat and garden
24,4487,Katica,0.58,female,Unknown Mix,2019-12-03,2019-12-03,2019-12-07,black,short,small,NaN,NaN,yes,NaN,NaN,NaN,NaN,both flat and garden
25,4491,Bethany,5.00,female,Chinese Shar-Pei Mix,2019-11-28,2019-11-28,2019-12-07,black and brown,short,medium,NaN,NaN,yes,NaN,NaN,NaN,NaN,both flat and garden
26,4486,Cotta,0.15,female,Staffordshire Terrier Mix,2019-12-01,2019-12-01,2019-12-07,brown and white,short,medium,NaN,NaN,yes,NaN,yes,yes,NaN,both flat and garden
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2910,25,Pongo,14.67,male,"Beagle, Dachshund Mix",2006-04-01,2007-05-01,2007-07-23,tricolor,short,small,NaN,NaN,yes,yes,yes,yes,NaN,both flat and garden
2912,21,Maggie,14.67,female,"German Dog, Labrador Retriever Mix",2006-07-01,2007-05-01,2007-07-23,black,short,large,NaN,NaN,yes,yes,yes,yes,NaN,both flat and garden
2913,2,Diego,13.67,male,Dachshund Mix,2007-04-01,2007-04-01,2007-05-21,red,short,small,NaN,yes,yes,yes,yes,yes,NaN,both flat and garden
2926,109,Kari,13.33,female,"German Pointer, Pointer Mix",2007-01-15,2007-01-15,2007-03-16,black and white,short,medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2928,110,Kavics,13.75,male,Pumi Mix,2007-01-15,2007-01-15,2007-03-17,striped,medium,medium,NaN,NaN,yes,yes,yes,yes,NaN,both flat and garden

In [76]:
dogs.fillna("not available")

,ID,name,age,sex,dog_breed,date_found,date_adoptable,date_posted,color,coat_type,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
0,23807,Gida,0.25,female,Unknown Mix,2019-12-10,2019-12-11,2019-12-11,red,short,small,no,not available,not available,not available,not available,not available,not available,not available
1,533,Frida És Ricsi,0.17,female,Unknown Mix,2019-12-01,2019-12-01,2019-12-09,black and white,short,small,no,not available,yes,yes,yes,yes,yes,not available
2,23793,not available,4.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,saddle back,short,medium,no,not available,not available,not available,not available,not available,not available,not available
3,23795,not available,1.00,male,Unknown Mix,2019-12-08,2019-12-23,2019-12-08,yellow-brown,medium,medium,no,not available,not available,not available,not available,not available,not available,not available
4,23806,Amy,2.00,female,French Bulldog Mix,2019-12-10,2019-12-11,2019-12-11,black,short,small,no,not available,not available,not available,not available,not available,not available,not available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2932,118,Fodri,16.92,male,Unknown Mix,2003-12-25,2003-12-25,2006-03-22,yellow-brown,short,medium,no,no,yes,yes,no,yes,no,garden
2933,262,Csibi,17.33,female,Staffordshire Terrier Mix,2004-08-27,2004-08-27,2005-07-08,striped,short,large,yes,not available,not available,not available,not available,not available,not available,not available
2934,4,Konrád,18.17,male,Unknown Mix,2005-09-21,2005-09-21,2005-10-26,black,short,medium,no,not available,not available,not available,not available,not available,not available,not available
2935,141,Kölni,17.17,male,Unknown Mix,2004-11-27,2004-11-27,2005-05-02,black and brown,medium,medium,no,not available,not available,not available,not available,not available,not available,not available
2936,248,Kedves,16.08,male,"German Shepherd Dog, Hound Mix",2005-04-02,2005-04-02,2005-06-30,sable,short,medium,yes,not available,yes,not available,yes,yes,not available,both flat and garden